version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: chmod +x boot.sh
    command: ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8001"
    depends_on:
      - db
